In [2]:
import numpy as np

In [3]:
# buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[2, 5, 5], [0, 0, 1]])
X

array([[2, 5, 5],
       [0, 0, 1]])

In [4]:
# tampilkan ukuran dari matrix X
X.shape

(2, 3)

In [5]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X[:,0]

array([2, 0])

In [7]:
# tampilkan seluruh elemen dari baris kedua dari matrix X
X[1,:]

array([0, 0, 1])

2. ulangi soal nomor 1 menggunakan Pytorch

In [6]:
import torch

In [8]:
X_pt = torch.tensor([[2, 5, 5], [0, 0, 1]])
X_pt

tensor([[2, 5, 5],
        [0, 0, 1]])

In [9]:
X_pt.shape

torch.Size([2, 3])

In [10]:
X_pt[:,0]

tensor([2, 0])

In [11]:
X_pt[1,:]

tensor([0, 0, 1])

3. ulangi soal nomor 1 menggunakan Tensorflow

In [12]:
import tensorflow as tf

In [13]:
X_tf = tf.Variable([[2, 5, 5], [0, 0, 1]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[2, 5, 5],
       [0, 0, 1]], dtype=int32)>

In [14]:
X_tf.shape

TensorShape([2, 3])

In [15]:
X_tf[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 0], dtype=int32)>

In [16]:
X_tf[1,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 0, 1], dtype=int32)>