In [6]:
import numpy as np

x = 1
y = 1

M_np = np.array([[x, y, x],
                 [y, x, y],
                 [x, y, x]])

fro_np = np.linalg.norm(M_np, 'fro')

print("Matrix NumPy:\n", M_np)
print("Frobenius Norm:", fro_np)


Matrix NumPy:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
Frobenius Norm: 3.0


In [8]:
import torch

x = 1.
y = 1.

M_pt = torch.tensor([[x, y, x],
                     [y, x, y],
                     [x, y, x]])

fro_pt = torch.norm(M_pt, p='fro')

print("Matrix PyTorch:\n", M_pt)
print("Frobenius Norm:", fro_pt)


Matrix PyTorch:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
Frobenius Norm: tensor(3.)


In [9]:
import tensorflow as tf

x = 1.
y = 1.

M_tf = tf.constant([[x, y, x],
                    [y, x, y],
                    [x, y, x]])

fro_tf = tf.norm(M_tf)

print("Matrix TensorFlow:\n", M_tf)
print("Frobenius Norm:", fro_tf.numpy())


Matrix TensorFlow:
 tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
Frobenius Norm: 3.0
