In [1]:
import numpy as np

In [2]:
# buat vector x dengan ukuran 3x1
x = np.array([[0],
              [0],
              [1]])
x

array([[0],
       [0],
       [1]])

In [3]:
# hitung panjang vector x
len(x)

3

In [4]:
# tampilkan ukuran vector x
x.shape

(3, 1)

In [5]:
# tampilkan tipe data dari vector x
type(x)

numpy.ndarray

In [6]:
# akses elemen pertama dari vector x
x[0] # zero-indexed

array([0])

In [7]:
# tampilkan tipe data elemen pertama dari vector x
type(x[0])

numpy.ndarray

2. lakukan transpose pada vector x dan simpan pada variabel x_t

In [8]:
x_t = x.T
x_t

array([[0, 0, 1]])

In [9]:
# tampilkan ukuran dari vector x_t
x_t.shape

(1, 3)

In [10]:
# lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[5],
              [5],
              [1]])

y_t = y.T
y_t

array([[5, 5, 1]])

In [11]:
# tampilkan ukuran dari vector y_t
y_t.shape

(1, 3)

3. lakukan soal nomor 2 menggunakan pytorch dan tensorflow

# Pytorch

In [14]:
import torch as pt

In [15]:
x = pt.tensor([[0],
               [0],
               [1]])
x

tensor([[0],
        [0],
        [1]])

In [16]:
x_t = x.T
x_t

tensor([[0, 0, 1]])

In [17]:
x_t.shape

torch.Size([1, 3])

In [18]:
y = pt.tensor([[5],
               [5],
               [1]])
y

tensor([[5],
        [5],
        [1]])

In [19]:
y_t = y.T
y_t

tensor([[5, 5, 1]])

# TensorFlow

In [20]:
import tensorflow as tf

In [21]:
x = tf.constant([[0],
                 [0],
                 [1]])
x

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[0],
       [0],
       [1]], dtype=int32)>

In [22]:
x_t = tf.transpose(x)
x_t

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[0, 0, 1]], dtype=int32)>

In [23]:
y = tf.constant([[5],
                 [5],
                 [1]])
y

<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[5],
       [5],
       [1]], dtype=int32)>

In [24]:
y_t = tf.transpose(y)
y_t

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[5, 5, 1]], dtype=int32)>